/**
 * Source Map Utilities
 *
 * Maps WASM errors to AssemblyScript source locations using V8 stack traces + source maps.
 *
 * Approach: V8's Error.prepareStackTrace provides WAT (WebAssembly Text) line:column positions,
 * which can be mapped to AS source using the source maps generated by AS compiler.
 */

import { type RawSourceMap, SourceMapConsumer } from 'source-map';

import { debug } from '../util/debug.js';
import type { WebAssemblyCallSite } from '../types/types.js';
import { createPoolErrorFromAnyError } from '../util/pool-errors.js';
import { POOL_ERROR_NAMES } from '../types/constants.js';

export function parseSourceMap(sourceMap: string): RawSourceMap {
  // Remove sourceRoot if present to prevent source-map library from prepending it to paths
  //   AS compiler sets sourceRoot: "./output" which would make paths like "output/tests/..."
  //   instead of "tests/..." - these paths don't exist and won't be found by Vitest
  try {
    const sourceMapObj: RawSourceMap = JSON.parse(sourceMap);
    delete sourceMapObj.sourceRoot;
    return sourceMapObj;
  }
  catch (err) {
    throw createPoolErrorFromAnyError(
      `parseSourceMap error`,
      POOL_ERROR_NAMES.PoolError,
      err
    )
  }
}

/**
 * Extract structured call stack from V8 using Error.prepareStackTrace
 *
 * V8 provides a special API to access structured stack traces with line:column info.
 * This gives us WAT text positions which can be mapped to AS source via source maps.
 *
 * @param capturedError - Error object to extract stack from
 * @returns Array of V8 CallSite objects
 */
export function extractCallStack(capturedError: Error): NodeJS.CallSite[] {
  let stackTrace: NodeJS.CallSite[] = [];

  const originalPrepareStackTrace = Error.prepareStackTrace;
  Error.prepareStackTrace = (_err: Error, structuredStackTrace: NodeJS.CallSite[]) => {
    stackTrace = structuredStackTrace;
    return ''; // Return empty string to avoid modifying error.stack
  };

  // Access error.stack to trigger prepareStackTrace (result unused, just triggers callback)
  capturedError.stack;

  // Restore original
  Error.prepareStackTrace = originalPrepareStackTrace;

  return stackTrace;
}

/**
 * Create WebAssembly call site with source mapping
 *
 * Takes a V8 CallSite and maps it to AS source location if possible.
 *
 * @param callSite - V8 CallSite object from Error.prepareStackTrace
 * @param sourceMapJson - Source map consumer initialized with WASM source map
 * @returns Mapped call site or null if not a WASM call site
 */
export function createWebAssemblyCallSite(
  callSite: NodeJS.CallSite,
  sourceMapConsumer: SourceMapConsumer
): WebAssemblyCallSite | null {
  const fileName = callSite.getFileName();

  // Only process WASM call sites
  if (!fileName || !fileName.startsWith('wasm://')) {
    return null;
  }

  const watLine = callSite.getLineNumber();
  const watColumn = callSite.getColumnNumber();
  const functionName = callSite.getFunctionName() || 'wasm-function[unknown]';
  const debugString = `function: "${functionName}" | wasm: ${fileName}:${watLine}:${watColumn}`;

  // Try to map to source
  if (watLine && watColumn) {
    const original = sourceMapConsumer.originalPositionFor({
      line: watLine,
      column: watColumn
    });
  
    if (!original.source || original.line === null || original.column === null) {
      debug(`[SourceMap] Failed to map: ${debugString}`);
      return null;
    }

    debug(`[SourceMap] Mapped ${debugString} → source: ${original.source}:${original.line}:${original.column}`);
    
    const callSite: WebAssemblyCallSite = {
      functionName,
      location: {
        filePath: original.source,
        line: original.line,
        column: original.column
      }
    };

    return callSite;
  }

  debug(`[SourceMap] Failed to map: ${debugString}`);

  // Fallback to WAT position
  return {
    functionName,
    location: {
      filePath: fileName,
      line: watLine || -1,
      column: watColumn || -1
    }
  };
}
