/**
 * Generates the large coverage fixture.
 *
 * Produces a fixture with more instrumented functions than fit in a single
 * coverage-memory page. One 64KB WASM page holds 16,384 i32 (4-byte) counters,
 * so generating more functions than that forces coverage counters into a 2nd
 * page specifically, while also providing a large-scale workload that
 * stress-tests containment matching.
 *
 * We commit the generator rather than ~34k lines of generated AS: the fixture is
 * emitted into the gitignored `test-generated/` directory. This mirrors how
 * `scripts/setup-test-external.js` produces test scaffolding.
 *
 * This runs BEFORE vitest starts — it is discovered and executed by
 * `scripts/generate-passing-fixtures.js`, which the passing npm scripts invoke
 * ahead of `vitest run`, rather than being wired as a vitest `globalSetup`. A
 * `globalSetup` runs too late: vitest resolves the test-spec glob and the
 * coverage-include glob from the filesystem *before* the `globalSetup` phase, so
 * a fixture generated in a `globalSetup` doesn't exist when those globs run and
 * is silently skipped on the first run — i.e. always in CI, where every checkout
 * is clean and `test-generated/` is gitignored. Generating ahead of vitest
 * guarantees the files are on disk when both globs run.
 *
 * Paths resolve against the main repo via `import.meta.url`, so generation always
 * writes to the correct location, even though the executor may run while vitest
 * ultimately runs from the external sibling install directory (where its cwd
 * differs). The executor uses dynamic `import()` rather than bundling, so this
 * module's own `import.meta.url` stays accurate.
 *
 * Default-exports the generator function so it is discovered and executed by
 * `scripts/generate-passing-fixtures.js`.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// test/generators/ -> repo root is two levels up
const PROJECT_ROOT = resolve(__dirname, '../..');

// One 64KB WASM memory page holds 16,384 i32 (4-byte) coverage counters.
// Generate comfortably more than that so counters spill into a 2nd page. The
// count is overridable for tuning; the default keeps a clear margin over the
// boundary so the spill is guaranteed regardless of framework counter overhead.
const COUNTERS_PER_PAGE = 16_384;
const FIXTURE_FUNCTION_COUNT =
  Number(process.env.LARGE_FIXTURE_FN_COUNT) || COUNTERS_PER_PAGE + 1_000;

const GENERATED_ROOT = resolve(PROJECT_ROOT, 'test-generated');
const SRC_DIR = join(GENERATED_ROOT, 'assembly-src');
const TEST_DIR = join(GENERATED_ROOT, 'assembly');

const SRC_FILE = join(SRC_DIR, 'large-fixture.ts');
const PASS_TEST_FILE = join(TEST_DIR, 'large-fixture.test.ts');

const GENERATED_HEADER =
  '// AUTO-GENERATED by test/generators/large-fixture.js — do not edit.\n' +
  '// Regenerated into the gitignored test-generated/ directory on each test run.\n';

/**
 * Build the AS source: many trivial, non-inlined functions (one instrumented
 * function each at -O0) plus an aggregator that calls every one of them, so all
 * counters — including the high-index ones in page >=2 — are both instrumented
 * and executed.
 */
function buildSource() {
  const lines = [GENERATED_HEADER];
  // A function rather than a module-level `const = <literal>`: an AS module-level
  // const with a literal initializer lowers to a WASM global constant init with no
  // runtime block, so that statement can never be covered. A function body can — which
  // keeps the fixture at 100% statement/line coverage for the passing threshold.
  lines.push(`export function fixtureFunctionCount(): i32 { return ${FIXTURE_FUNCTION_COUNT}; }`);
  lines.push('');

  for (let i = 0; i < FIXTURE_FUNCTION_COUNT; i++) {
    lines.push(`function fixtureFn${i}(): i32 { return 1; }`);
  }

  lines.push('');
  lines.push('// Calls every fixture function so all counters are executed, not just');
  lines.push('// instrumented — this is what drives a store into a page >=2 counter.');
  lines.push('export function callAllFixtureFns(): i32 {');
  lines.push('  let sum: i32 = 0;');
  for (let i = 0; i < FIXTURE_FUNCTION_COUNT; i++) {
    lines.push(`  sum += fixtureFn${i}();`);
  }
  lines.push('  return sum;');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/** Passing scenario: default auto-sized coverage memory must not trap. */
function buildPassTest() {
  return `${GENERATED_HEADER}
import { test, expect } from "vitest-pool-assemblyscript/assembly";
import { callAllFixtureFns, fixtureFunctionCount } from "../assembly-src/large-fixture";

// Executes every instrumented function, including those whose coverage counters
// live in page >=2. With the default (auto-sized) coverage memory this must
// store without trapping.
test("large fixture: all instrumented functions execute without trapping", () => {
  expect(callAllFixtureFns()).toBe(fixtureFunctionCount());
});
`;
}

export default function generateLargeFixture() {
  mkdirSync(SRC_DIR, { recursive: true });
  mkdirSync(TEST_DIR, { recursive: true });

  writeFileSync(SRC_FILE, buildSource());
  writeFileSync(PASS_TEST_FILE, buildPassTest());

  console.log(
    `[large-fixture] Generated ${FIXTURE_FUNCTION_COUNT} functions ` +
    `into ${GENERATED_ROOT} (> ${COUNTERS_PER_PAGE}/page → spills to page >=2)`
  );
}
