name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # minimum supported version for this project
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run tc

      - name: Build
        run: npm run build

      - name: Setup External Test Directory
        run: npm run test:ext:setup

      - name: Test Passing Suite Externally
        run: npm run test:ext:pass
        
      - name: Test Meta Verify Suite Externally
        run: npm run test:ext:meta:verify

      - name: v3 - Setup External Test Directory
        run: npm run test:ext:setup:v3

      - name: v3 - Test Passing Suite Externally
        run: npm run test:ext:pass
        
      - name: v3 - Test Meta Verify Suite Externally
        run: npm run test:ext:meta:verify