name: Platform Tests (on-demand) - Windows

on:
  workflow_dispatch:

jobs:

  test-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-11-vs2026-arm]
        node-version: ['22', '24']
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          VITEST_AS_POOL_SKIP_NATIVE_BUILD: 1

      - name: Download Binaryen dependencies
        run: npm run setup-binaryen
      
      - name: Create prebuild
        run: npm run build:prebuild
      
      - name: Type check
        run: npm run tc

      - name: Build
        run: npm run build

      - name: Setup External Test Directory
        run: npm run test:ext:setup

      - name: Test Passing Suite Externally
        run: npm run test:ext:pass

      - name: Test Meta Verify Suite Externally
        run: npm run test:ext:meta:verify

      - name: v4 - Setup External Test Directory
        run: npm run test:ext:setup:v4

      - name: v4 - Test Passing Suite Externally
        run: npm run test:ext:pass
        
      - name: v4 - Test Meta Verify Suite Externally
        run: npm run test:ext:meta:verify

      - name: v3 - Setup External Test Directory
        run: npm run test:ext:setup:v3

      - name: v3 - Test Passing Suite Externally
        run: npm run test:ext:pass
        
      - name: v3 - Test Meta Verify Suite Externally
        run: npm run test:ext:meta:verify
